name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      
    steps:
    
    - name: Install dependencies
      run: |
        apk add --no-cache git cmake make g++ libc-dev doxygen
        
    - name: Checkout repo 
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON 

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build/ -V

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Publish Documentation
      uses: peaceiris/actions-gh-pages@d38d8b34e3c4631f1ebfec2a11dafd7761e48e98
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html  
        allow_empty_commit: true
        force_orphan: true

