name: Doxygen Documentation

on: [push]

jobs:
  build:
    runs-on: alpine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apk update doxygen

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Publish Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html  # replace with your OUTPUT_DIRECTORY from Doxyfile
